# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Lovelace dedicated configuration file
lovelace: !include lovelace.yaml

# SmartIR Integration
# smartir:

# Powercalc Integration

# powercalc:
#   enable_autodiscovery: true

# FFmpeg Integration
ffmpeg:

# https://www.home-assistant.io/integrations/system_health/
system_health:
# logger:
#   default: warning
#   logs:
#     custom_components.hacs: error
#     custom_components.smartir: error
#     custom_components.xiaomi_miot: error
#     custom_components.device_tracker: error
#     custom_components.samsungtv_smart: error
#     homeassistant.loader: error
#     homeassistant.const: error
#     homeassistant.components.media_player: error
#     homeassistant.components.alarm_control_panel: error
#     homeassistant.components.climate: error
#     homeassistant.components.humidifier: error
#     homeassistant.components.device_tracker: error
#     homeassistant.helpers.entity: warning

#View all events in a logbooks
# logbook:

# camera:
#   - name: Xiaomi Vacuum Map
#     platform: xiaomi_cloud_map_extractor
#     host: !secret cleaner_ipv4
#     token: !secret cleaner_token
#     username: !secret xiaomi_cloud_username
#     password: !secret xiaomi_cloud_password
#     country: cn
#     draw: ["all"]
#     attributes:
#       - calibration_points

# media_player:
#   - platform: smartir
#     name: Living room TV
#     unique_id: tv
#     device_code: 1061
#     controller_data: remote.rm4_pro
#     power_sensor: binary_sensor.tv_power
#   - platform: samsungtv_tizen
#     host: !secret tv_ipv4
#     mac: !secret tv_mac
#     app_list: '{"Jellyfin": "AprZAARz4r.Jellyfin", "Twitch": "3202203026841", "Crunchyroll": "qXuEoRvlCp.Crunchyroll"}'

climate:
  - platform: smartir
    name: Home AC
    unique_id: ac
    device_code: 1180
    controller_data: remote.rm4_pro
    temperature_sensor: sensor.entrydoor_weather_temperature_3        
    humidity_sensor: sensor.entrydoor_weather_humidity_3
    power_sensor: binary_sensor.ac_power

# ifttt:
#   key: !secret ifttt_api_key

homeassistant:
  debug: true
  customize: !include_dir_merge_named customize/
  # Customize entities matching a pattern
  customize_glob:
    "sensor.lumi_lumi_weather_*_temperature":
      icon: mdi:thermometer
    "light.*":
      icon: mdi:lightbulb-outline
    "sensor.lumi_lumi_weather_humidity_*":
      icon: mdi:water
    "binary_sensor.lumi_lumi_sensor_motion_aq2_occupancy_*":
      icon: mdi:motion-sensor
    "sensor.*rx_gb*":
      icon: mdi:wifi-arrow-down
      unit_of_measurement: GB
      device_class: data_rate
    "sensor.*tx_gb*":
      icon: mdi:wifi-arrow-up
      unit_of_measurement: GB
      device_class: data_rate
    "sensor.*sleep_confidence*":
      icon: mdi:sleep
      unit_of_measurement: "%"
    "sensor.*battery_level*":
      unit_of_measurement: "%"
      device_class: battery
light:
  - platform: group
    name: "Hallway Lights"
    entities:
      - light.hallway_1
      - light.hallway_2
      - light.hallway_3
      - light.hallway_4
      - light.hallway_5
      - light.hallway_6

  - platform: group
    name: "Liveroom Lights"
    entities:
      - light.liveroom_1
      - light.liveroom_2
      - light.liveroom_3
      - light.liveroom_4
      - light.liveroom_5

  - platform: group
    name: "Bathroom Lights"
    entities:
      - light.bathroom_1

  - platform: group
    name: "Yeelight"
    entities:
#     - light.yeelight_strip8_0x19eba68d
#     - light.yeelight_color4_0x13f2130d
#     - light.yeelink_strip8_39e2_light
#     - light.yeelight_strip6_0x13f2ddcb
#     - light.yeelink_color4_974a_light
#     - light.yeelink_color4_974a_light
#     - light.yeelink_strip8_39e2_light
      - light.yeelight_color4_0x123e1046
      - light.philips_strip3_4a09_light
      - light.yeelight_strip6_0x13f2ddcb

  - platform: group
    name: "Home Lights"
    entities:
      - light.yeelight
      - light.liveroom_lights
      - light.hallway_lights
#      - light.bathroom_lights
http:
  ip_ban_enabled: false
  use_x_forwarded_for: true
  trusted_proxies:
    - 103.21.244.0/22
    - 103.22.200.0/22
    - 192.168.1.0/24
    - 192.168.0.0/24
    - 10.43.0.0/16
    - 10.42.0.0/16
    - 2001:cafe:42:1::/112
    - 100.64.0.0/10
    # Cloudflare Ipv4 IP Ranges
    - 103.31.4.0/22
    - 141.101.64.0/18
    - 108.162.192.0/18
    - 190.93.240.0/20
    - 188.114.96.0/20
    - 197.234.240.0/22
    - 198.41.128.0/17
    - 162.158.0.0/15
    - 104.16.0.0/13
    - 104.24.0.0/14
    - 172.0.0.0/8
    - 131.0.72.0/22
    - fd7a:115c:a1e0:ab12::/64
tts:
  - platform: google_translate
api:
automation: !include_dir_merge_list automations/
sensor: !include_dir_merge_named sensors
script: !include_dir_merge_named scripts/
scene: !include scenes.yaml
frontend:
  themes: !include_dir_merge_named themes
  # extra_module_url:
  #   - /hacsfiles/custom-sidebar/custom-sidebar-yaml.js
# notify:
#   - name: "smtp2go"
#     platform: smtp
#     server: !secret smtp_server
#     port: 8025
#     timeout: 60
#     sender: !secret smtp_sender
#     encryption: starttls
#     username: !secret smtp_username
#     password: !secret smtp_password
#     recipient:
#       - !secret smtp_recipient1
#       - !secret smtp_recipient2
#     sender_name: "Home Assistant"
