# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:
# person:
#   - name: Gruber
#     id: gruber_real
#     device_trackers:
#       - device_tracker.iphone_13_mini_gruber
#       - device_tracker.rodrigos_iphone
#       - device_tracker.macbook
#       - device_tracker.rodrigos_iphone_2
#       - device_tracker.windows_desktop
#       - device_tracker.gruber
recorder:
  db_url: !secret external_database
  purge_keep_days: 180

media_source:
# Sun integration w/ elevation values

# Lovelace dedicated configuration file
lovelace: !include lovelace.yaml

# SmartIR Integration
smartir:
# Powercalc Integration
powercalc:
  enable_autodiscovery: true
# FFmpeg Integration
ffmpeg:
# Map Integration
map:
# https://www.home-assistant.io/integrations/system_health/
system_health:
logger:
  default: warning
  logs:
    custom_components.hacs: error
    custom_components.smartir: error
    custom_components.xiaomi_miot: error
    custom_components.device_tracker: error
    custom_components.samsungtv_smart: error
    homeassistant.loader: error
    homeassistant.const: error
    homeassistant.components.media_player: error
    homeassistant.components.alarm_control_panel: error
    homeassistant.components.climate: error
    homeassistant.components.humidifier: error
    homeassistant.components.device_tracker: error
    homeassistant.helpers.entity: warning

#View all events in a logbooks
# logbook:

# Vultr VPS Cloud Integration
# vultr:
#   api_key: !secret vultr_api_key

camera:
  # - name: Home Camera
  #   platform: ffmpeg
  #   input: -rtsp_transport tcp -i rtsp://wyze-bridge.homeassistant.svc.cluster.local:8554/studiocam
  # - name: Hall Camera
  #   platform: ffmpeg
  #   input: !secret hall_camera_uri
  # - name: Camera1
  #   platform: proxy
  #   entity_id: camera.wyze_bridge_homeassistant_svc_cluster_local
  #   max_stream_width: 360
  #   max_image_width: 720
  - name: Xiaomi Vacuum Map
    platform: xiaomi_cloud_map_extractor
    host: !secret cleaner_ipv4
    token: !secret cleaner_token
    username: !secret xiaomi_cloud_username
    password: !secret xiaomi_cloud_password
    country: cn
    draw: ["all"]
    attributes:
      - calibration_points

stream:
  ll_hls: true
  part_duration: 0.75
  segment_duration: 6

media_player:
  - platform: smartir
    name: Living room TV
    unique_id: tv
    device_code: 1061
    controller_data: remote.rm4_pro
    power_sensor: binary_sensor.tv_power
  - platform: samsungtv_tizen
    host: !secret tv_ipv4
    mac: !secret tv_mac
    app_list: '{"Jellyfin": "AprZAARz4r.Jellyfin", "Twitch": "3202203026841", "Crunchyroll": "qXuEoRvlCp.Crunchyroll"}'

climate:
  - platform: smartir
    name: Home AC
    unique_id: ac
    device_code: 1180
    controller_data: remote.rm4_pro
    temperature_sensor: sensor.entrydoor_weather_temperature_3
    humidity_sensor: sensor.entrydoor_weather_humidity_3
    power_sensor: binary_sensor.ac_power

ifttt:
  key: !secret ifttt_api_key

homeassistant:
  name: Mainframe
  latitude: !secret ha_latitude
  longitude: !secret ha_longitude
  elevation: !secret ha_elevation
  unit_system: metric
  temperature_unit: C
  time_zone: America/Sao_Paulo
  currency: BRL
  customize: !include_dir_merge_named customize/
  auth_providers:
    - type: homeassistant
    - type: trusted_networks
      allow_bypass_login: true
      trusted_networks:
        - 10.43.0.0/16
        - 2001:cafe:42:1::/112
        - 10.42.0.0/16
        - 2001:cafe:42:0::/56
        - 192.168.1.0/24
        - 192.168.0.0/24
        - 10.0.1.0/24
        - fd7a:115c:a1e0:ab12::/64
        # Tailscale network
        - 100.64.0.0/10
        - 127.0.0.1
        - ::1
  # Customize entities matching a pattern
  customize_glob:
    "sensor.lumi_lumi_weather_*_temperature":
      icon: mdi:thermometer
    "light.*":
      icon: mdi:lightbulb-outline
    "sensor.lumi_lumi_weather_humidity_*":
      icon: mdi:water
    "binary_sensor.lumi_lumi_sensor_motion_aq2_occupancy_*":
      icon: mdi:motion-sensor

light:
  - platform: group
    name: "Home Lights"
    entities:
      - light.yeelight_strip8_0x19eba68d
      - light.yeelight_color4_0x123e1046
      - light.yeelight_color4_0x13f2130d
      - light.yeelight_strip6_0x13f2ddcb
      - light.philips_strip3_4a09_light

device_tracker:
  - platform: iphonedetect
    consider_home: 60
    new_device_defaults:
      track_new_devices: true
    hosts:
      Gruber: 192.168.1.9

api:

http:
  server_host: 0.0.0.0
  ip_ban_enabled: false
  use_x_forwarded_for: true
  cors_allowed_origins:
    - "*"
    - http://home.gruber.dev.br
    - https://home.gruber.dev.br
  trusted_proxies:
    - !secret public_ip
    # Cloudflare Ipv4 IP Ranges
    - 173.245.48.0/20
    - 103.21.244.0/22
    - 103.22.200.0/22
    - 103.31.4.0/22
    - 141.101.64.0/18
    - 108.162.192.0/18
    - 190.93.240.0/20
    - 188.114.96.0/20
    - 197.234.240.0/22
    - 198.41.128.0/17
    - 162.158.0.0/15
    - 104.16.0.0/13
    - 104.24.0.0/14
    - 172.64.0.0/13
    - 131.0.72.0/22

tts:
  - platform: google_translate

automation: !include_dir_merge_list automations
sensor: !include_dir_merge_named sensors
script: !include_dir_merge_named scripts/
scene: !include scenes.yaml
frontend:
  themes: !include_dir_merge_named themes
  extra_module_url:
    - /config/www/community/custom-sidebar/custom-sidebar-yaml.js
# notify:
#   - platform: ios
#   - name: "smtp2go"
#     platform: smtp
#     server: !secret smtp_server
#     port: 8025
#     timeout: 60
#     sender: !secret smtp_sender
#     encryption: starttls
#     username: !secret smtp_username
#     password: !secret smtp_password
#     recipient:
#       - !secret smtp_recipient1
#       - !secret smtp_recipient2
#     sender_name: "Home Assistant"
