order:
  - new_item: true
    item: test
    href: "/dashboard-test"
    icon: mdi:earth
    order: 0
  - item: overview
    order: 1
  - new_item: true
    item: Integrations
    href: "/config/integrations"
    icon: mdi:puzzle
    order: 2
  - new_item: true
    item: Entities
    href: "/config/entities"
    icon: mdi:hexagon-multiple
    order: 3
  - new_item: true
    item: Automations
    href: "/config/automation"
    icon: mdi:robot
    order: 4
  - item: terminal
    order: 5
  - item: hacs
    order: 6
    notification: '[[[ state_attr("sensor.hacs", "repositories").length || "" ]]]'
  - item: config
    bottom: true
    order: 7
  - item: logbook
    bottom: true
    order: 8
  - new_item: true
    item: Logs
    bottom: true
    href: "/config/logs"
    icon: mdi:math-log
    order: 9
  - item: developer tools
    name: Dev tools
    icon: mdi:tools
    bottom: true
    order: 10
  - item: history
    hide: true
  - item: snapshots
    hide: true
  - item: backups
    hide: true
  - item: map
    hide: true
  - item: energy
    hide: true
  - item: media browser
    hide: true
exceptions:
  - user:
    - Jim Hawkins
    - Long John Silver
    base_order: false
    order: []
id: example
title: "Homelab"
sidebar_editable: true
styles: |
  @import url('https://fonts.googleapis.com/css2?family=Inter:wght@100..900&display=swap');
  body {
    font-family: 'Inter', sans-serif !important;
    font-optical-sizing: auto;
    font-weight: 400;
    font-style: normal;
    font-variation-settings: "slnt" 0;
    font-size: 16px;
  }
  html {
    --sidebar-background-color: #000000 !important;
    --app-header-background-color: #333333;
    --text-primary-color: #FFFFFF;
    --outline-hover-color: #A1FFFF;
  }
  ha-sidebar {
    background-color: #000000 !important;
  }
  .menu .title { 
    display: none;
  }
  a[role='option'] .item-text { 
    color: #A1FFFF; 
  }
