order:
  - new_item: true
    item: test
    href: "/dashboard-test"
    icon: mdi:earth
    target: _blank
    order: 0
  - item: overview
    order: 1
  - new_item: true
    item: Integrations
    href: "/config/integrations"
    icon: mdi:puzzle
    order: 2
  - new_item: true
    item: Entities
    href: "/config/entities"
    icon: mdi:hexagon-multiple
    order: 3
  - new_item: true
    item: Automations
    href: "/config/automation"
    icon: mdi:robot
    order: 4
  - item: terminal
    order: 5
  - item: hacs
    order: 6
    notification: '[[[ state_attr("sensor.hacs", "repositories").length || "" ]]]'
  - item: config
    bottom: true
    order: 7
  - item: logbook
    bottom: true
    order: 8
  - new_item: true
    item: Logs
    bottom: true
    href: "/config/logs"
    icon: mdi:math-log
    order: 9
  - item: developer tools
    name: Dev tools
    icon: mdi:tools
    bottom: true
    order: 10
  - item: history
    hide: true
  - item: snapshots
    hide: true
  - item: backups
    hide: true
  - item: map
    hide: true
  - item: energy
    hide: true
  - item: media browser
    hide: true
exceptions:
  - user:
    - Jim Hawkins
    - Long John Silver
    base_order: false
    order: []
id: example
title: "Homelab"
sidebar_editable: false
styles: ".menu .title { color: red; } a[role='option'] .item-text { color: blue; }"
