
id: example
title: "Homelab"
sidebar_editable: true
order:
  - new_item: true
    item: test
    href: "/dashboard-test"
    icon: mdi:earth
    order: 0
  - item: overview
    order: 1
  - new_item: true
    item: Integrations
    href: "/config/integrations"
    icon: mdi:puzzle
    order: 2
  - new_item: true
    item: Entities
    href: "/config/entities"
    icon: mdi:hexagon-multiple
    order: 3
  - new_item: true
    item: Automations
    href: "/config/automation"
    icon: mdi:robot
    order: 4
  - item: terminal
    order: 5
  - item: hacs
    order: 6
    notification: |
      [[[
        const outdatedHacsEntities = Object.values(entities.update).filter(
          (entity) => entity.platform === 'hacs' && is_state(entity.entity_id, 'on')
        );
        return outdatedHacsEntities.length || '';
      ]]]
  - item: config
    bottom: true
    order: 7
  - new_item: true
    item: Server Controls
    href: "/config/server_control"
    icon: mdi:server
    bottom: true
    order: 8
  - item: logbook
    bottom: true
    order: 9
  - new_item: true
    item: Logs
    bottom: true
    href: "/config/logs"
    icon: mdi:math-log
    order: 10
  - item: developer tools
    name: Dev tools
    icon: mdi:tools
    bottom: true
    order: 11
  - item: history
    hide: true
  - item: snapshots
    hide: true
  - item: backups
    hide: true
  - item: map
    hide: true
  - item: energy
    hide: true
  - item: media browser
    hide: true
id: my_sidebar
