order:
  - item: overview
    order: 1
  - new_item: true
    item: Integrations
    href: "/config/integrations"
    icon: mdi:puzzle
    order: 2
  - new_item: true
    item: Test
    name: "Home Dashboard"
    href: "/dashboard-test"
    icon: mdi:hexagon-multiple
    order: 3
  - new_item: true
    item: Logs
    bottom: true
    href: "/config/logs"
    icon: mdi:math-log
    order: 4
  - item: developer tools
    name: Dev tools
    icon: mdi:tools
    bottom: true
    order: 5
  - item: history
    hide: true
title: "sidebar"
sidebar_editable: "no"
styles: ".menu .title { color: red; } a[role="option"] .item-text { color: blue; }"
