title: Mainframe
views:
  - theme: Google Dark Theme
    title: Floorplan
    path: floorplan
    type: panel
    badges: []
    cards:
      - type: custom:floorplan-card
        full_height: true
        show_side_bar: false
        show_app_header: false
        config:
          image:
            - min_width: 0
              location: /config/lovelace/floorplan/images/default.svg
              cache: true
            - min_width: 1024
              location: /config/lovelace/floorplan/images/default-wide.svg
              cache: true
          image_mobile:
            - min_width: 0
              location: /config/lovelace/floorplan/images/mobile.svg
              cache: true
            - min_width: 1024
              location: /config/lovelace/floorplan/images/mobile-wide.svg
              cache: true
          stylesheet: /config/lovelace/floorplan/stylesheet.css
          log_level: info
          console_log_level: info
          defaults:
            hover_action: hover-info
            tap_action: more-info
          rules:
            - entity: light.yeelight_lights
              element: light.yeelight_lights
              state_action:
                action: call-service
                service: floorplan.image_set
                service_data: /local/floorplan/examples/home/light_${entity.state}.svg
              tap_action: toggle
            - entities:
                - light.home_lights
              tap_action:
                action: navigate
                navigation_path: /lovelace/lights
              state_action:
                - action: call-service
                  service: floorplan.style_set
                  service_data: |
                    >
                      var elements = [
                        `${entity.entity_id}`,
                        `${entity.entity_id}.gradient_color_0`,
                      ];

                      var color = 'rgb(0, 0, 0)';
                      var opacity = 0;

                      if (entity.state === 'on') {
                        if (entity.attributes.color_temp) {
                          var rgb = util.color.miredToRGB(entity.attributes.color_temp);
                          color = `rgb(${rgb[0]}, ${rgb[1]}, ${rgb[2]})`;
                          opacity = 1;
                        }
                        else if (entity.attributes.rgb_color) {
                          var rgb = entity.attributes.rgb_color;
                          color = `rgb(${rgb[0]}, ${rgb[1]}, ${rgb[2]})`;
                          opacity = 1;
                        }
                      }
                      var style = `fill: ${color}; stop-color: ${color}; stop-opacity: ${opacity};`;

                      return {
                        elements: elements,
                        style: style,
                      };s
